//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class andinoshopEntities1 : DbContext
    {
        public andinoshopEntities1()
            : base("name=andinoshopEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<order> order { get; set; }
    
        public virtual ObjectResult<Productos_Result2> Productos_Result2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Productos_Result2>("Productos_Result2");
        }
    
        public virtual ObjectResult<Usuario_Result> Usuario_Result()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario_Result>("Usuario_Result");
        }
    
        public virtual ObjectResult<Orders_Result1> Orders_Result1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Orders_Result1>("Orders_Result1");
        }
    }
}
