//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class andinoshopEntities1 : DbContext
    {
        public andinoshopEntities1()
            : base("name=andinoshopEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<inventory> inventory { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
    
        public virtual ObjectResult<Usuario_Result> Usuario_Result()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario_Result>("Usuario_Result");
        }
    
        public virtual ObjectResult<OrdenGuardar_Result> OrdenGuardar_Result(Nullable<int> order_id, string consecutive, Nullable<System.DateTime> date_order, Nullable<System.DateTime> date_delivered, Nullable<int> client_id, Nullable<int> address_id, Nullable<decimal> subtotal, Nullable<decimal> tax_total, Nullable<decimal> delivery, Nullable<int> status_id, Nullable<decimal> total, string validate)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var consecutiveParameter = consecutive != null ?
                new ObjectParameter("consecutive", consecutive) :
                new ObjectParameter("consecutive", typeof(string));
    
            var date_orderParameter = date_order.HasValue ?
                new ObjectParameter("date_order", date_order) :
                new ObjectParameter("date_order", typeof(System.DateTime));
    
            var date_deliveredParameter = date_delivered.HasValue ?
                new ObjectParameter("date_delivered", date_delivered) :
                new ObjectParameter("date_delivered", typeof(System.DateTime));
    
            var client_idParameter = client_id.HasValue ?
                new ObjectParameter("client_id", client_id) :
                new ObjectParameter("client_id", typeof(int));
    
            var address_idParameter = address_id.HasValue ?
                new ObjectParameter("address_id", address_id) :
                new ObjectParameter("address_id", typeof(int));
    
            var subtotalParameter = subtotal.HasValue ?
                new ObjectParameter("subtotal", subtotal) :
                new ObjectParameter("subtotal", typeof(decimal));
    
            var tax_totalParameter = tax_total.HasValue ?
                new ObjectParameter("tax_total", tax_total) :
                new ObjectParameter("tax_total", typeof(decimal));
    
            var deliveryParameter = delivery.HasValue ?
                new ObjectParameter("delivery", delivery) :
                new ObjectParameter("delivery", typeof(decimal));
    
            var status_idParameter = status_id.HasValue ?
                new ObjectParameter("status_id", status_id) :
                new ObjectParameter("status_id", typeof(int));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            var validateParameter = validate != null ?
                new ObjectParameter("Validate", validate) :
                new ObjectParameter("Validate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrdenGuardar_Result>("OrdenGuardar_Result", order_idParameter, consecutiveParameter, date_orderParameter, date_deliveredParameter, client_idParameter, address_idParameter, subtotalParameter, tax_totalParameter, deliveryParameter, status_idParameter, totalParameter, validateParameter);
        }
    
        public virtual ObjectResult<InventarioGuardar_Result> InventarioGuardar_Result(Nullable<int> inventory_id, Nullable<int> product_id, Nullable<int> user_id, Nullable<double> quantity, Nullable<int> measure_id, Nullable<System.DateTime> date_created, string validate)
        {
            var inventory_idParameter = inventory_id.HasValue ?
                new ObjectParameter("inventory_id", inventory_id) :
                new ObjectParameter("inventory_id", typeof(int));
    
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(double));
    
            var measure_idParameter = measure_id.HasValue ?
                new ObjectParameter("measure_id", measure_id) :
                new ObjectParameter("measure_id", typeof(int));
    
            var date_createdParameter = date_created.HasValue ?
                new ObjectParameter("date_created", date_created) :
                new ObjectParameter("date_created", typeof(System.DateTime));
    
            var validateParameter = validate != null ?
                new ObjectParameter("Validate", validate) :
                new ObjectParameter("Validate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InventarioGuardar_Result>("InventarioGuardar_Result", inventory_idParameter, product_idParameter, user_idParameter, quantityParameter, measure_idParameter, date_createdParameter, validateParameter);
        }
    
        public virtual ObjectResult<Orders_Result3> Orders_Result3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Orders_Result3>("Orders_Result3");
        }
    
        public virtual ObjectResult<OrderDetailGuardar_Result> OrderDetailGuardar_Result(Nullable<int> order_detail, Nullable<int> order_id, Nullable<int> product_id, Nullable<double> quantity, Nullable<decimal> price, Nullable<decimal> tax, Nullable<decimal> subtotal, string validate)
        {
            var order_detailParameter = order_detail.HasValue ?
                new ObjectParameter("order_detail", order_detail) :
                new ObjectParameter("order_detail", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(double));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(decimal));
    
            var taxParameter = tax.HasValue ?
                new ObjectParameter("tax", tax) :
                new ObjectParameter("tax", typeof(decimal));
    
            var subtotalParameter = subtotal.HasValue ?
                new ObjectParameter("subtotal", subtotal) :
                new ObjectParameter("subtotal", typeof(decimal));
    
            var validateParameter = validate != null ?
                new ObjectParameter("Validate", validate) :
                new ObjectParameter("Validate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderDetailGuardar_Result>("OrderDetailGuardar_Result", order_detailParameter, order_idParameter, product_idParameter, quantityParameter, priceParameter, taxParameter, subtotalParameter, validateParameter);
        }
    
        public virtual ObjectResult<Inventario_Result3> Inventario_Result3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Inventario_Result3>("Inventario_Result3");
        }
    
        public virtual ObjectResult<Productos_Result3> Productos_Result3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Productos_Result3>("Productos_Result3");
        }
    
        public virtual ObjectResult<OrderDetail_Result1> OrderDetail_Result1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderDetail_Result1>("OrderDetail_Result1");
        }
    }
}
