//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int order_id { get; set; }
        public string consecutive { get; set; }
        public System.DateTime date_order { get; set; }
        public Nullable<System.DateTime> date_delivered { get; set; }
        public int address_id { get; set; }
        public decimal subtotal { get; set; }
        public decimal tax_total { get; set; }
        public decimal delivery { get; set; }
        public int status_id { get; set; }
        public decimal total { get; set; }
    
        public virtual client client { get; set; }
    }
}
