//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    
    public partial class Productos_Result4
    {
        public int product_id { get; set; }
        public string name { get; set; }
        public string name_brand { get; set; }
        public int brand_id { get; set; }
        public int category_id { get; set; }
        public string description { get; set; }
        public string name_category { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    }
}
